# Generated by Django 3.2.5 on 2021-08-09 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ('created',)},
        ),
    ]
